# Generated by Django 3.1.4 on 2020-12-10 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='author',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='title',
        ),
        migrations.AddField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libapp.books'),
        ),
    ]
